name: Deploy

on:
  push:
    branches:
      - master # Changing the branch here would also work

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{c6ffbc92-58bb-4d58-8eeb-9c7778b27c1d}}
          heroku_app_name: "meetingwebapplication" #Must be unique in Heroku
          heroku_email: "thamizhselan85@gmail.com"
          env_file: ".env"
          procfile: "web: npm start"
          run: heroku auth:whoami
          justlogin: true
        env:
          HD_FIREBASE_API_KEY: ${{secrets.FIREBASE_API_KEY}}
          HD_RANDOM_DATA: "Hello"